name: social_embed_webview
description: Provide a widget to easily embed social media post in flutter using web embed feature by the platform.
version: 1.0.0
homepage: https://github.com/aker99/social_embed_webview

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter:
  url_launcher: ^6.3.1
  localstorage: ^5.0.0
  http: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

