name: social_embed_webview
description: Provide a widget to easily embed social media post in flutter using web embed feature by the platform.
version: 0.3.1
homepage: https://github.com/aker99/social_embed_webview

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.22.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^1.0.7
  url_launcher: ^5.7.10 
  localstorage: ^3.0.0
  http: ^0.12.2


dev_dependencies:
  flutter_test:
    sdk: flutter

